### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by xt0032rus** [ProjectInfinity-X/official_devices#1]
### Device you want to apply for

Xiaomi 13(fuxi)

### Device Tree Sources

https://github.com/xt0032rus/android_device_xiaomi_xiaomi13
https://github.com/xt0032rus/proprietary_vendor_xiaomi13
https://github.com/xt0032rus/android_kernel_xiaomi_sm8550
https://github.com/xt0032rus/android_kernel_xiaomi_sm8550-modules

### Number of ROM's you maintain officially/unofficially, also name them

Project Blaze Unofficial 

### Any Exceptions/special concern?

No

### Telegram username

xt0032rus

### GitHub username

xt0032rus

**Comment by tejas101k** [comment]
[The Initial Commit ](https://github.com/xt0032rus/android_device_xiaomi_xiaomi13/commit/93e6ff942b359fdad1c8762d5b09236d1b050ad5) clearly doesn't look like a skeleton tree structure from scratch. There's already tons of material like parts and stuff are already included in this initial commit without the proper authorships or history! Can you justify that?

**Comment by xt0032rus** [comment]
It was taken from gitlab https://gitlab.com/nguyenhung9xdev2024/android_device_xiaomi_xiaomi13
