### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by devbx** [ProjectInfinity-X/official_devices#100]
### Device you want to apply for

Redmi 12C (earth)

### Device Tree Sources

https://github.com/devbx/android_device_xiaomi_earth
https://github.com/devbx/android_kernel_xiaomi_earth
https://github.com/mt6768-dev/proprietary_vendor_xiaomi_earth

### Number of rom(s) you maintain, also name them stating official or unofficial

3 (all UNOFFCIAL)

### Telegram username / or any alternative medium to reach you

https://t.me/devbx0 / devbx@proton.me

### GitHub username

devbx

**Comment by tejas101k** [comment]
Too early for official status!
