### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by muhammadrafiasyddiq** [ProjectInfinity-X/official_devices#101]
### Device you want to apply for

POCO M5 (STONE)  / REDMI 11 PRIME (ROCK)

### Device Tree Sources

https://github.com/muhammadrafiasyddiq/android_device_xiaomi_stone

https://github.com/muhammadrafiasyddiq/android_vendor_xiaomi_stone

https://github.com/muhammadrafiasyddiq/android_kernel_xiaomi_stone

### Number of rom(s) you maintain, also name them stating official or unofficial

3 Unofficial

### Any Exceptions/special concern?

No Source Kernel Availabe Because This GKI I Use Prebuilt Like GKI Other Devices

### Telegram username / or any alternative medium to reach you

@H0AMSI

### GitHub username

muhammadrafiasyddiq

**Comment by tejas101k** [comment]
Already being maintained by https://github.com/Drpto.

**Comment by tejas101k** [comment]
ohh alright my bad. DM (t.me/tejas101k)
