### ISSUE TITLE
Ashish Kumar

### ISSUE THREAD

**Issue by ashish04235** [ProjectInfinity-X/official_devices#102]
### Device you want to apply for

Realme 8 (nashc)

### Device Tree Sources

https://github.com/nashc-dev/android_kernel_realme_nashc.git

### Number of rom(s) you maintain, also name them stating official or unofficial

2

### Any Exceptions/special concern?

But only a issue 
The github id i am submitting with  is my new one so you will not be able to see my contributions 
The id from which i will make roms is mentioned at username 
want to make roms with this ID thats why id id that so 
Currently developing new trees for my device that's why no URLs attached above
sorry for inconvenience
https://github.com/bengris32/releases (can check for my released roms)

### Telegram username / or any alternative medium to reach you

@ashishbestiit

### GitHub username

bengris32
https://github.com/bengris32

**Comment by ashish04235** [comment]
Currently developing new trees for my device that's why no URLs attached above 
sorry for inconvenience

**Comment by tejas101k** [comment]
Never thought I would ever witness an impersonation scam on github just to maintain a damn rom! 
@bengris32 Be aware.

**Comment by Vlad55432** [comment]
> https://github.com/bengris32/releases (can check for my released roms)

dude, it's not your repo

**Comment by plarfman** [comment]
You are way too obvious to impersonating the main developer still

**Comment by Aeron-Aeron** [comment]
bro just causally impersonating someone else
