### ISSUE TITLE
New maintainer for Realme 7/Narzo 20 Pro/ Narzo 30 4g (salaa)

### ISSUE THREAD

**Issue by ShitijHalder** [ProjectInfinity-X/official_devices#104]
### Device you want to apply for

Realme 7/Narzo 20 Pro/ Narzo 30 4g (salaa)

### Device Tree Sources

Device Tree: https://github.com/ShitijHalder/device_realme_salaa
Vendor Tree: https://github.com/ShitijHalder/vendor_realme_salaa
Kernel Tree: https://github.com/ShitijHalder/kernel_realme_salaa

### Number of rom(s) you maintain, also name them stating official or unofficial

I maintain Project Blaze and DerpfestOS unofficially and HorizonOS as official.

### Any Exceptions/special concern?

Nothing much, last time I applied and it got rejected but this time I am experienced and I really want this rom to be in my list and this time I am pretty sure I can manage maintaining trees properly and there won't be any problem with building.

### Telegram username / or any alternative medium to reach you

@shitijnotop

### GitHub username

ShitijHalder

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
