### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by PiotrZPL** [ProjectInfinity-X/official_devices#108]
### Device you want to apply for

Mi 10T (apollo)

### Device Tree Sources

https://github.com/PiotrZPL/device_xiaomi_apollo/tree/lineage-21
https://github.com/PiotrZPL/vendor_xiaomi_apollo
https://github.com/PiotrZPL/device_xiaomi_sm8250-common/tree/lineage-21
https://github.com/PiotrZPL/vendor_xiaomi_sm8250-common
https://github.com/LineageOS/android_kernel_xiaomi_sm8250

### Number of rom(s) you maintain, also name them stating official or unofficial

LineageOS and DerpFest - both unofficial

### Telegram username / or any alternative medium to reach you

https://t.me/PiotrZPL

### GitHub username

PiotrZPL

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
