### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Allien10X** [ProjectInfinity-X/official_devices#14]
### Device you want to apply for

Redmi Note 12 Pro5G (ruby)

### Device Tree Sources

https://github.com/Allien10X/android_device_xiaomi_ruby

https://github.com/Allien10X/android_vendor_xiaomi_ruby

https://github.com/Allien10X/android_kernel_xiaomi_mt6877

### Number of ROM's you maintain officially/unofficially, also name them

I am maintaining 2 unofficial ROMs.

### Any Exceptions/special concern?

no there's not

### Telegram username

travisexe

### GitHub username

Allien10X

**Comment by tejas101k** [comment]
![image](https://github.com/ProjectInfinity-X/official_devices/assets/128741893/39da9ba4-cc69-449d-b566-73922a293878)
improper commit history!

Also many unauthored commits. Doesn't seem mature enough for official pov! Feel free to apply once you improve.

**Comment by Allien10X** [comment]
I suggest you look again, I edited all of them and I don't have any unauthorized commits. If so, are these my own commits?

**Comment by Allien10X** [comment]
I suggest you look again, I edited all of them and I don't have any unauthorized commits. If so, are these my own commits?

**Comment by tejas101k** [comment]
> I suggest you look again, I edited all of them and I don't have any unauthorized commits. If so, are these my own commits?

![image](https://github.com/ProjectInfinity-X/official_devices/assets/128741893/7f7f28bd-8f6e-41b1-8f2b-c381fb2f79af)
i still don't see the fpushes
