### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by aleeeee1** [ProjectInfinity-X/official_devices#140]
### Device you want to apply for

Xiaomi Mi A3 (laurel_sprout)

### Device Tree Sources

https://github.com/aleeeee1/device_xiaomi_laurel_sprout dt
https://github.com/aleeeee1/vendor_xiaomi_laurel_sprout vendor
https://github.com/aleeeee1/device_xiaomi_laurel_sprout-kernel (kernel is prebuilt)

### Number of rom(s) you maintain, also name them stating official or unofficial

1, Blaze UNOFFICIAL.

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

(how do i do unofficial build without the source?)

### Any Exceptions/special concern?

I need to apply some patches to make the rom work with my device.
[build_make](https://github.com/aleeeee1/build_make-blaze/commit/fb1b0a18c66952c6f04929215cecb8c357b3a52d)
[tinycompass](https://github.com/aleeeee1/android_external_tinycompress/commit/4dc972f471802ed2931ef650398b2d7fe8c71ab5)
[gralloc, in qcom-caf/sm8150/display](https://github.com/Pos-trinket/hardware_qcom_display/commit/12c2d06c4c59c4f521c5a993c4aa8f628e0549ab)

probably something else i will face at build time

Notification LED is not working with the common xiaomi light aidl, but it is working for charging, low battery

### Telegram username / or any alternative medium to reach you

bakkaq

### GitHub username

aleeeee1

**Comment by tejas101k** [comment]
You can compile source for unofficial.
https://t.me/ProjectInfinityX/504

Also make compitable with aidl light patchsets. If it's really not possible, revert the hardware/xiaomi patches that are breaking it or simply just use in-tree light hal. In short kindly try making everything functional

**Comment by tejas101k** [comment]
closing for the time being.
