### ISSUE TITLE
New maintainer for Motorola Edge 30 (dubai)

### ISSUE THREAD

**Issue by Fraaxius** [ProjectInfinity-X/official_devices#142]
### Device you want to apply for

Motorola Edge 30 (dubai)

### Device Tree Sources

https://github.com/Fraaxius/android_device_motorola_dubai (branches 14 & 14-gapps)
https://github.com/Fraaxius/android_device_motorola_sm7325-common
https://github.com/Fraaxius/kernel_motorola_sm7325
https://github.com/Fraaxius/vendor_motorola_dubai
https://github.com/Fraaxius/vendor_motorola_sm7325-common

### Number of rom(s) you maintain, also name them stating official or unofficial

2 atm (PixelOS and InfinityX). Both unofficials.

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

https://t.me/MotoEdge30Updates/194

### Any Exceptions/special concern?

As of August 2020, I have started to delve into the world of Android, being able to be a contributor on a series of Motorola devices, like:

- Moto G7 Power/Play/Plus
- Moto G9 Plus
- Moto X4
- Moto Z2 Force

I have been part of the RevengeOS team in 2021 for Moto G7 Plus, standing out for the responsibility of keeping the ROM updated and looking for some kind of solutions to bugs that occur. If it is allowed to add another exception, I have contributed to the device tree in LineageOS too. (on Dubai btw).

I hope that what I wrote above can be better understood, thank you very much in advance. :)

### Telegram username / or any alternative medium to reach you

https://t.me/Francirijillo

### GitHub username

github.com/Fraaxius

**Comment by Fraaxius** [comment]
To add: I understand that I previously made an issue here, but I have closed it because I needed to rebase some changes on both DTs. 
Thank you very much for your understanding.

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)

**Comment by Fraaxius** [comment]
> DM (t.me/tejas101k)

Sent.
