### ISSUE TITLE
Apply For Maintainer ship

### ISSUE THREAD

**Issue by DelightReza** [ProjectInfinity-X/official_devices#15]
### Device you want to apply for

Moto G9/Play (guamp)

### Device Tree Sources

https://github.com/moto-guamp

### Number of ROM's you maintain officially/unofficially, also name them

LineageOS

### Any Exceptions/special concern?

NA

### Telegram username

DelightReza

### GitHub username

DelightReza

**Comment by tejas101k** [comment]
Hi, DM (t.me/tejas101k)
