### ISSUE TITLE
New maintainer (N4bi10p)

### ISSUE THREAD

**Issue by n4bi10p** [ProjectInfinity-X/official_devices#17]
### Device you want to apply for

Realme x7 Max 5g (Cupida)

### Device Tree Sources

https://github.com/oplus-ossi-development/android_device_oplus_cupida
https://github.com/oplus-ossi-development/android_device_oplus_mt6893-common
https://github.com/oplus-ossi-development/android_kernel_oplus_mt6893
https://github.com/orgs/oplus-ossi-development/repositories

### Number of ROM's you maintain officially/unofficially, also name them

unofficially - ProjectMatrixx , PixelExtended

### Any Exceptions/special concern?

Nope nothing.

### Telegram username

N4bi10p

### GitHub username

n4bi10p

**Comment by tejas101k** [comment]
Any piece of work you can show that you've personally contributed to the trees? because i couldn't find any.

**Comment by cat658011** [comment]
really, he not make any

**Comment by n4bi10p** [comment]
This is my forks

https://github.com/n4bi10p/android_device_oplus_cupida
https://github.com/n4bi10p/android_device_oplus_mt6893-common

**Comment by cat658011** [comment]
Bro not know git
