### ISSUE TITLE
It will happen this time 

### ISSUE THREAD

**Issue by Allien10X** [ProjectInfinity-X/official_devices#18]
### Device you want to apply for

Redmi Note 12Pro5G (ruby)

### Device Tree Sources

Device Tree: https://github.com/Allien10X/android_device_xiaomi_ruby
-
Vendor Tree: https://github.com/Allien10X/android_vendor_xiaomi_ruby
-
Kernel Tree: https://github.com/Allien10X/android_kernel_xiaomi_mt6877

### Number of ROM's you maintain officially/unofficially, also name them

I have been accepted for AlphaDroid official, I will put my repositories there soon and I am also making Project-Matrixx unofficially.

### Any Exceptions/special concern?

Just a determined rom compiler

### Telegram username

travisexe

### GitHub username

Allien10X

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
