### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ankitstha** [ProjectInfinity-X/official_devices#19]
### Device you want to apply for

OnePlus 7 Pro (guacamole)

### Device Tree Sources

https://github.com/ankitstha/device_oneplus_sm8150-common
https://github.com/ankitstha/device_oneplus_guacamole
https://github.com/yaap/kernel_oneplus_sm8150

### Number of ROM's you maintain officially/unofficially, also name them

ProjectBlaze Official, ProjectEverest Official

### Any Exceptions/special concern?

i use vendor tree's from yaap so I havent mentioned their links.

### Telegram username

c00chiemilker

### GitHub username

ankitstha

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
