### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Pyrtle93** [ProjectInfinity-X/official_devices#2]
### Device you want to apply for

Pixel 7 series (cheetah) (lynx) (panther)

### Device Tree Sources

https://github.com/Matrixx-Devices/android_device_google_gs101
https://github.com/Matrixx-Devices/device_google_gs-common
https://github.com/Matrixx-Devices/device_google_gs201
https://github.com/Matrixx-Devices/device_google_pantah
https://github.com/Matrixx-Devices/device_google_lynx
https://github.com/Matrixx-Devices/device_google_panther
https://github.com/Matrixx-Devices/device_google_cheetah
https://github.com/Matrixx-Devices/vendor_google_cheetah
https://github.com/Matrixx-Devices/vendor_google_lynx
https://github.com/Matrixx-Devices/vendor_google_panther

### Number of ROM's you maintain officially/unofficially, also name them

Matrixx

### Any Exceptions/special concern?

Have been maintaining for about 3 years now officially. I have officially maintained ancient, xtended, derpfest and now matrixx!

### Telegram username

@Pyrtle93

### GitHub username

Pyrtle93

**Comment by Pyrtle93** [comment]
> pixel 7a already reserved I'M working on source with team for pixel bringup

That's fine, I own the 7 pro anyways

**Comment by Pyrtle93** [comment]
> > > pixel 7a already reserved I'M working on source with team for pixel bringup
> > 
> > 
> > That's fine, I own the 7/7 pro anyways
> > sure mate !
> > nice
> > i owned pixel7a 7p but i will do
> > only 7a here

Hopefully I can get in, it's a great rom

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
