### ISSUE TITLE
Project Infinity X Maintainership for OnePlus Nord (avicii)

### ISSUE THREAD

**Issue by sreeshankark** [ProjectInfinity-X/official_devices#20]
### Device you want to apply for

OnePlus Nord (avicii)

### Device Tree Sources

Device Tree: https://github.com/sreeshankark/android_device_oneplus_avicii-derpfest
Kernel Source with KSU) :https://github.com/sreeshankark/android_kernel_oneplus_avicii
Kernel Source (without KSU): https://github.com/sreeshankark/android_kernel_oneplus_sm7250
Vendor blobs: https://github.com/sreeshankark/android_vendor_oneplus_avicii-14
Ancient OS DT: https://github.com/sreeshankark/android_device_oneplus_avicii-ancientos

### Number of ROM's you maintain officially/unofficially, also name them

Number of ROM's: 2; Ancient OS [officially]; Derpfest [unofficially]

### Any Exceptions/special concern?

Ancient OS ROM source isn't up-to-date. But I have mentioned my Ancient OS device tree link to check my commits. The Derpfest DT has only bringup from Lineage OS 14 DT. So, if you want to check my commit history kindly go through Ancient OS DT. I will be using my latest Derpfest DT to compile Project Infinity ROM. Also I am maintaining a custom kernel with KSU support for my device. If you don't allow to release build with KSU support then I am happy to use normal kernel without KSU support. Thank you😊

### Telegram username

sksanju0910

### GitHub username

sreeshankark

**Comment by tejas101k** [comment]
DM (t.me/tejas101k).
