### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JoseMCCGit** [ProjectInfinity-X/official_devices#21]
### Device you want to apply for

Motorola Edge 30 (dubai)

### Device Tree Sources

https://github.com/JoseMCCGit/android_kernel_motorola_sm7325
https://github.com/JoseMCCGit/android_device_motorola_dubai
https://github.com/JoseMCCGit/android_vendor_motorola_dubai

### Number of ROM's you maintain officially/unofficially, also name them

Project Matrixx Unofficial

### Any Exceptions/special concern?

All actual changes of device tree are in first commit

### Telegram username

josemcc0705

### GitHub username

JoseMCCGit

**Comment by JoseMCCGit** [comment]
Can you give me a reason?, Is for fix it

**Comment by tejas101k** [comment]
Pasting complete device tree here n there without authorships!
https://github.com/JoseMCCGit/android_device_motorola_dubai/commit/b4a6381ec72ef33762d17496f2cfc65987b8fd1f
