### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by GustavoCaruzoGoncalves** [ProjectInfinity-X/official_devices#211]
### Device you want to apply for

Moto G84 5G (bangkk)

### Device Tree Sources

https://github.com/sm6375-Caruzo

### Number of rom(s) you maintain, also name them stating official or unofficial

I built a lot of unofficial ROMs for bangkk community, but actually I don't maintain any of them, they were single builds. I already built two builds of InfinityX and I'm building the new 2.2 version right now.

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

https://t.me/caruzoromschannel/17

### Any Exceptions/special concern?

The tree is made by AnandSuresh02 (his GitHub username), I forked it and made my changes to be sure somethings that were not working, would work with these changes.

### Telegram username / or any alternative medium to reach you

Telegram: @gustavocaruzo
XDA: https://xdaforums.com/m/caruzoontop.12049065/

### GitHub username

GustavoCaruzoGoncalves

**Comment by tejas101k** [comment]
Hello there,

First of all Thank you for considering applying for official maintainership.

Unfortunately, the requirements for becoming an official maintainer have not been met at this time. We believe you might need a bit more experience for the role right now.

However, you can always gain experience by working with Git, maintaining proper authorships, understanding the code structure, and writing appropriate commit messages. Once you feel ready, you're welcome to apply again anytime!

Best regards
