### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by swiitchOFF** [ProjectInfinity-X/official_devices#225]
### Device you want to apply for

Xiaomi 11T Pro (vili)

### Device Tree Sources

1) https://github.com/Spanish-or-Vanish/device_xiaomi_vili/tree/infi
2) https://github.com/Spanish-or-Vanish/android_device_xiaomi_sm8350-common/tree/infi
3) https://github.com/Spanish-or-Vanish/vendor_xiaomi_sm8350-common
4) https://github.com/swiitch-OFF-Lab/vendor_xiaomi_vili
5) https://github.com/swiitch-OFF-Lab/kernel_xiaomi_sm8350

### Number of rom(s) you maintain, also name them stating official or unofficial

Currently official crDroid A14(EOL), A15 my other unofficial CLO (paranoid Android) A14 builds now EOL

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

n/a

### Any Exceptions/special concern?

not released Project Infinity X because was fixing Dolby else you can review my trees.
Note: i made some other unofficial roms only for testing purpose and adaption for A15 tree

### Telegram username / or any alternative medium to reach you

@MIUI_users_r_GAY

### GitHub username

 swiitchOFF

**Comment by tejas101k** [comment]
DM t.me/tejas101k
