### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mnrniloy** [ProjectInfinity-X/official_devices#24]
### Device you want to apply for

OnePlus7,OnePlus7T and OnePlus7T pro

### Device Tree Sources

https://github.com/mnrniloy/device_oneplus_hotdog.git
https://github.com/mnrniloy/device_oneplus_hotdogb.git
https://github.com/mnrniloy/device_oneplus_guacamoleb.git
https://github.com/mnrniloy/device_oneplus_sm8150-common.git

### Number of ROM's you maintain officially/unofficially, also name them

4 Officially (AfterLife, BananaDroid) Unofficially (RisingOS A13,DerpFest A14))

### Any Exceptions/special concern?

Nope
If i face any problem please help me
I'm kinda noob😅

### Telegram username

@mnrniloy0

### GitHub username

https://github.com/mnrniloy

**Comment by tejas101k** [comment]
You're already committed to 4 projects. We will highly suggest you not to take more commitments and perform your best and improve on what you're currently doing.
