### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by MySelly** [ProjectInfinity-X/official_devices#241]
### Device you want to apply for

Redmi Note 13 Pro 5G / Poco X6 5G

### Device Tree Sources

https://github.com/orgs/aosp-garnet/repositories

### Number of rom(s) you maintain, also name them stating official or unofficial

Only pixelos now before i maintaining yaap too (both unoff)

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

i did a14 and a15 but didnt relesed it publicly

### Any Exceptions/special concern?

nope

### Telegram username / or any alternative medium to reach you

@mysellysenpai

### GitHub username

myselly

**Comment by tejas101k** [comment]
the link to resources provided doesn't reflect any work of yours?
