### ISSUE TITLE
Applying again 

### ISSUE THREAD

**Issue by Musafir02** [ProjectInfinity-X/official_devices#247]
### Device you want to apply for

Redmi note 10 pro 

### Device Tree Sources

https://github.com/Musafir02/device_xiaomi_sweet.git
https://github.com/Musafir02/kernel_xiaomi_sm6150.git
https://github.com/Musafir02/vendor_xiaomi_sweet.git
https://github.com/Musafir02/device_xiaomi_sm6150-common.git
https://github.com/Musafir02/vendor_xiaomi_sm6150-common.git

### Number of rom(s) you maintain, also name them stating official or unofficial

1 unofficial core, full gapps

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

https://t.me/RoyalOSsweet/98

### Any Exceptions/special concern?

Bro this time I have learned that you said

### Telegram username / or any alternative medium to reach you

@Musafir1875

### GitHub username

Musafir02

**Comment by tejas101k** [comment]
I would recommend you not hurrying for the OFFICIAL status, I see you're new and still learning.. I hope you continue to learn better first then consider about maintaining your commitment officially..

Reply given in #238 still applies here
