### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by bezke** [ProjectInfinity-X/official_devices#250]
### Device you want to apply for

Redmi Note 13 pro 5G / Poco X6 (garnet)

### Device Tree Sources

[https://github.com/bezkemods/android_device_xiaomi_garnet](url)
[https://github.com/bezkemods/proprietary_vendor_xiaomi_garnet](url)
[https://github.com/bezkemods/device_xiaomi_garnet-kernel](url)

### Number of rom(s) you maintain, also name them stating official or unofficial

2

### Link to your one released Infinity-X Unofficial Build (must be a link of a platform eg. telegram or xda)

https://t.me/garnet_updates/673

### Any Exceptions/special concern?

I am excited to join the Project Infinity-X team. I have over 13 years of experience in building Android ROMs, with a specialization in Xiaomi devices. I have a deep understanding of their specifications and functionality, and over the years, I have successfully fixed numerous issues. I am eager to contribute my expertise and knowledge to the success of the project.

### Telegram username / or any alternative medium to reach you

https://t.me/bezke1

### GitHub username

bezke

**Comment by bezke** [comment]
Sorry,,,,I forgot the most important thing:
@chuspita is handing over the official development.
Thank you.

**Comment by tejas101k** [comment]
Hi, first of all thanks for applying..
But "unmoved21" from your community has already taken garnet maintainership.. few days back

**Comment by bezke** [comment]
Thx the answer!
