### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hasan6034** [ProjectInfinity-X/official_devices#29]
### Device you want to apply for

Redmi 10 (Selene)

### Device Tree Sources

https://github.com/hasan6034/android_device_xiaomi_selene
https://github.com/TelegramAt25/yuki_kernel_xiaomi_selene
https://github.com/hasan6034/legacy_vendor_xiaomi_selene

### Number of ROM's you maintain officially/unofficially, also name them

9

### Any Exceptions/special concern?

No

### Telegram username

hasan6034

### GitHub username

hasan6034

**Comment by cat658011** [comment]
Hey!

Thanks for the submission, feedback is as follows:

Device tree

1. Use bringup instead https://github.com/hasan6034/android_device_xiaomi_selene/commit/1e7e947ad725ce77f1c412eed1f5524c98cb6338 and https://github.com/hasan6034/android_device_xiaomi_selene/commit/cd84f7b09c9ecea1b1900363403c88ee23b1eb53
2. Missing authorship https://github.com/hasan6034/android_device_xiaomi_selene/commit/bbeae1d00bda35ef93debd85bb2522adf1ec73ba https://github.com/hasan6034/android_device_xiaomi_selene/commit/38405b5957b008d934d9130c10960c0917791624(use cherry-pick instead Co-Authored-by:)
3. https://github.com/hasan6034/android_device_xiaomi_selene/commit/4c76fac77a157a7a76957a6ac81e4cd0d9add519 https://github.com/hasan6034/android_device_xiaomi_selene/commit/8b4edc1372df8a593f1bed6cd0ac675a39b3b173 https://github.com/hasan6034/android_device_xiaomi_selene/commit/8508d473b5d1d41c7bf90c8b10559a5cb6bb8951 https://github.com/hasan6034/android_device_xiaomi_selene/commit/566292bb85a33c751cef2ba92944b8c402ebff0e https://github.com/hasan6034/android_device_xiaomi_selene/commit/c8ed319e3be603838a492c60fa9ee631ca3a1471 https://github.com/hasan6034/android_device_xiaomi_selene/commit/2fa8b732cf193710cbf0dd44e21579d4c8498b46 https://github.com/hasan6034/android_device_xiaomi_selene/commit/559069dbe998cd8e9398052ab6aaad1f6b630080 why exists?
4. https://github.com/hasan6034/android_device_xiaomi_selene/commit/695bb226c76fe1e7763fff97b7d127a3cd0cc7e9 https://github.com/hasan6034/android_device_xiaomi_selene/commit/303b0e266a9e76f8173a8470bdb397b044eea9e0 incorrect bringup


Thanks, when you have these worked out and answers to the questions, feel free to follow up and we can work on getting it forked!
