### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by matt0301** [ProjectInfinity-X/official_devices#3]
### Device you want to apply for

OnePlus 7T

### Device Tree Sources

https://github.com/arkhan-madness/device_oneplus_sm8150-common
https://github.com/arkhan-madness/device_oneplus_hotdogb
https://github.com/arkhan-madness/vendor_oneplus_sm8150-common
https://github.com/arkhan-madness/vendor_oneplus_hotdogb
https://github.com/arkhan-madness/hardware_oneplus
https://github.com/Codecity001/Neptune_kernel_sm8150_oneplus

### Number of ROM's you maintain officially/unofficially, also name them

1 - Derp

### Any Exceptions/special concern?

Yes, all the GitHub links, be sure to see 14 branch

### Telegram username

matt0301

### GitHub username

matt0301

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
