### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by seisdr** [ProjectInfinity-X/official_devices#32]
### Device you want to apply for

Realme gt neo 2

### Device Tree Sources

https://github.com/Blackmanx/android_hardware_oplus
https://github.com/Blackmanx/android_device_realme_sm8250-common
https://github.com/Blackmanx/android_device_realme_bitra
https://github.com/Blackmanx/android_vendor_realme_bitra
https://github.com/Blackmanx/android_vendor_realme_sm8250-common
https://github.com/Blackmanx/kernel_realme_sm8250

### Number of ROM's you maintain officially/unofficially, also name them

superior extended

### Any Exceptions/special concern?

No

### Telegram username

@Spiral09

### GitHub username

seisdr

**Comment by cat658011** [comment]
1. Not need add hardware
2. I see you not contributed to device

**Comment by tejas101k** [comment]
Too early for the official status! Couldn't see anything conclusive about your work by the resources you have provided
