### ISSUE TITLE
New maintainer For Redmi 12 5G / Poco M6 Pro 5G (sky)

### ISSUE THREAD

**Issue by suvojit213** [ProjectInfinity-X/official_devices#34]
### Device you want to apply for

Redmi 12 5G/ Poco M6 pro 5G (sky)

### Device Tree Sources

https://github.com/suvojit213/device_xiaomi_sky.git
https://github.com/suvojit213/vendor_xiaomi_sky.git
https://github.com/suvojit213/device_xiaomi_sky-kernel.git

### Number of ROM's you maintain officially/unofficially, also name them

2 Evolution X (Unofficial), Awaken OS (Unofficial)

### Any Exceptions/special concern?

No

### Telegram username

suvojeet_sengupta

### GitHub username

suvojit213

**Comment by cat658011** [comment]
Hey!

Thanks for the submission, feedback is as follows:

All good

Thanks, for you attention for Infinity-X project!
