### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mnrniloy** [ProjectInfinity-X/official_devices#37]
### Device you want to apply for

OnePlus7T pro(hotdog)

### Device Tree Sources

https://github.com/mnrniloy/device_oneplus_hotdog.git
https://github.com/mnrniloy/device_oneplus_sm8150-common.git
https://github.com/mnrniloy/vendor_oneplus_hotdog.git
https://github.com/mnrniloy/vendor_oneplus_sm8150-common.git

### Number of ROM's you maintain officially/unofficially, also name them

1 Officially AfterLife

### Any Exceptions/special concern?

Nope

### Telegram username

@mnrniloy0

### GitHub username

https://github.com/mnrniloy

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
