### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by shantanupc** [ProjectInfinity-X/official_devices#4]
### Device you want to apply for

Redmi Note 8 Pro (begonia)

### Device Tree Sources

https://github.com/shantanupc/device_redmi_begonia
https://github.com/saikrishna1504/kernel_xiaomi_mt6785
https://github.com/begonia-dev/android_hardware_mediatek
https://github.com/Saikrishna1504/vendor_redmi_begonia
https://github.com/begonia-dev/android_vendor_redmi_begonia-ims
https://github.com/Saikrishna1504/device_mediatek_sepolicy
https://github.com/Trinity-ROMS/android_vendor_redmi_begonia-firmware

### Number of ROM's you maintain officially/unofficially, also name them

Unofficial AlphaDroid

### Any Exceptions/special concern?

I have my own device to build roms and I'm building since A13 QPR 2

### Telegram username

@Shantzzzzz

### GitHub username

shantanupc

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
