### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by oghe3003** [ProjectInfinity-X/official_devices#40]
### Device you want to apply for

POCO F4

### Device Tree Sources

https://github.com/oghe3003/device_xiaomi_munch-infi
https://github.com/oghe3003/device_xiaomi_sm8250-common-infi

### Number of ROM's you maintain officially/unofficially, also name them

3 roms

### Any Exceptions/special concern?

official Ancient. Unofficial RisingOS and Unofficial SparkOS

### Telegram username

oghe3003

### GitHub username

oghe3003

**Comment by tejas101k** [comment]
Already maintained ig?
https://github.com/ProjectInfinity-X/vendor_infinity/blob/QPR2/infinity.devices#L19
