### ISSUE TITLE
New maintainer for Realme 7/Narzo 20 Pro/ Narzo 30 4g (salaa)

### ISSUE THREAD

**Issue by ShitijHalder** [ProjectInfinity-X/official_devices#43]
### Device you want to apply for

Realme 7/Narzo 20 Pro/ Narzo 30 4g (salaa)

### Device Tree Sources

Device Tree: https://github.com/ShitijHalder/device_realme_salaa
Vendor Tree: https://github.com/ShitijHalder/vendor_realme_salaa
Kernel Tree: https://github.com/ShitijHalder/kernel_realme_salaa

### Number of ROM's you maintain officially/unofficially, also name them

2 roms unofficially: DerpfestOS and Project Blaze

### Any Exceptions/special concern?

i started building for this device since 1-2 months ago and i am still learning git and other things properly.

### Telegram username

@shitijnotop

### GitHub username

ShitijHalder

**Comment by tejas101k** [comment]
I would recommend you to get a bit seasoned first with your compilations before considering official.
