### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by subhagamer** [ProjectInfinity-X/official_devices#55]
### Device you want to apply for

Realme X7 Max

### Device Tree Sources

https://github.com/oplus-ossi-development

DT,KT,VT etc are present here.

### Number of ROM's you maintain officially/unofficially, also name them

0

### Any Exceptions/special concern?

I can release one build per month

The device is on MTK chipset, namely MTK Dimensity 1200

### Telegram username

Zatvio

### GitHub username

subhagamer

**Comment by tejas101k** [comment]
I couldn't spot a signle contribution of yours on the resources link you have provided, can you show something added to resources by you?

**Comment by subhagamer** [comment]
> I couldn't spot a signle contribution of yours on the resources link you have provided, can you show something added to resources by you?

Check the commit history of 
https://github.com/oplus-ossi-development/android_device_oplus_mt6893-common/commits/lineage-21/

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
