### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Shivamingale3** [ProjectInfinity-X/official_devices#62]
### Device you want to apply for

Motorola Edge 30 Fusion (tundra)

### Device Tree Sources

Device: https://github.com/Shivamingale3/android_device_motorola_tundra
Vendor: https://gitlab.com/shivamingale3/vendor-motorola-tundra 
Kernel: https://github.com/Shivamingale3/kernel_motorola_tundra

### Number of ROM's you maintain officially/unofficially, also name them

1. Unofficial Project-Matrixx for tundra 2. Unofficial Project Awaken for tundra 3. Unofficial DerpfestAOSP for tundra 4. Unofficial CherishOS for tundra 5. Unofficial RisingOS for tundra

### Any Exceptions/special concern?

Device does not have a separate recovery partition So, there are no TWRP or other custom recoveries for this device, Either fastboot packages or boot, dtbo, vendor_boot for recovery.  I have my own server & Device, also a tester with a device. Used to maintain Superior-Extended unofficial and now want to officially maintain its successor. Bit less experienced but trying my best. [My Unofficial Builds](https://sourceforge.net/projects/shivam-ingale-s-tundra/files/).

### Telegram username

[Shivamingale](https://t.me/Shivamingale)

### GitHub username

Shivamingale3

**Comment by tejas101k** [comment]
too many maintained projects, I don't think you would be able to manage time to maintain another project. Will you?

**Comment by Shivamingale3** [comment]
> too many maintained projects, I don't think you would be able to manage time to maintain another project. Will you?

I am mostly free. Also my users have shifted to Project Matrixx So I'll stop maintaining other ROMs except Matrixx and RisingOS. So, I think there will be pretty much time to maintain Infinity X. Also I'll  do whatever to try this ROM.

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
