### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Shivamingale3** [ProjectInfinity-X/official_devices#7]
### Device you want to apply for

Motorola Edge 30 Fusion (tundra)

### Device Tree Sources

https://github.com/Shivamingale3/android_device_motorola_tundra.git
https://github.com/Shivamingale3/kernel_motorola_tundra.git
https://gitlab.com/shivamingale3/vendor-motorola-tundra
https://github.com/Shivamingale3/android_hardware_motorola.git
https://github.com/LineageOS/android_system_qcom.git

### Number of ROM's you maintain officially/unofficially, also name them

1. Unofficial Project-Matrixx for tundra 2. Unofficial Project Awaken for tundra 3. Unofficial DerpfestAOSP for tundra 4. Unofficial CherishOS for tundra 5. Unofficial Superior-Extended for tundra

### Any Exceptions/special concern?

I have my own server & Device, also a tester with a device. Used to maintain Superior-Extended unofficial and now want to officially maintain its successor. Bit less experienced but trying my best. [My Unofficial Builds](https://sourceforge.net/projects/shivam-ingale-s-tundra/files/)

### Telegram username

[Shivamingale](https://t.me/Shivamingale
)

### GitHub username

Shivamingale3

**Comment by tejas101k** [comment]
Immature resources! Too early for the official status

**Comment by Shivamingale3** [comment]
@tejas101k any suggestions for improvement
