### ISSUE TITLE
New maintainer for Xiaomi Redmi Note 12 4G (Tapas & Topaz)

### ISSUE THREAD

**Issue by AspectPower** [ProjectInfinity-X/official_devices#72]
### Device you want to apply for

Xiaomi Redmi Note 12 4G (Tapas & Topaz)

### Device Tree Sources

https://github.com/BaranAspect-Development/device_xiaomi_sm6225-common
https://github.com/BaranAspect-Development/device_xiaomi_topaz
https://github.com/BaranAspect-Development/vendor_xiaomi_topaz
https://github.com/BaranAspect-Development/device_xiaomi_topaz-kernel
https://github.com/BaranAspect-Development/device_xiaomi_sepolicy
https://github.com/BaranAspect-Development/vendor_xiaomi_sm6225-common
https://github.com/BaranAspect-Development/hardware_xiaomi

https://github.com/BaranAspect-Development/manifest-infinity
Manifest Added;
https://github.com/SM6225-AD/vendor_qcom_opensource_agm
https://github.com/SM6225-AD/vendor_qcom_opensource_arpal-lx
https://github.com/SM6225-AD/hardware_qcom_audio-ar
https://github.com/SM6225-AD/vendor_qcom_opensource_data-ipa-cfg-mgr
https://github.com/SM6225-AD/vendor_qcom_opensource_dataipa
https://github.com/SM6225-AD/hardware_qcom_display
https://github.com/SM6225-AD/hardware_qcom_media
https://github.com/itsnouralawad/android_hardware_qcom-caf_commo

### Number of ROM's you maintain officially/unofficially, also name them

1, Unofficialy LineageOS, did 4 updates.

### Any Exceptions/special concern?

Hello! I don't think i have any exception or special concerns.

Thank you!

### Telegram username

@BaranTR1

### GitHub username

AspectPower

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
