### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by dpenra** [ProjectInfinity-X/official_devices#73]
### Device you want to apply for

Redmi note 10

### Device Tree Sources

https://github.com/Xiaomi-Redmi-Note-10/device_xiaomi_sunny.git
https://github.com/Xiaomi-Redmi-Note-10/kernel_xiaomi_sunny.git
https://github.com/Xiaomi-Redmi-Note-10/vendor_xiaomi_sunny.git

### Number of ROM's you maintain officially/unofficially, also name them

2, evolution x 9.0, risingos 3.2
https://t.me/RedmiNote10_Community/425228

https://t.me/RedmiNote10ID/831689

https://mega.nz/file/a5wjkJ7C#hn0rDBOmO-nPmd1qkSlKC1VOjLrzllnPe_3llo5NoeE

https://drive.google.com/drive/folders/1-08zI_26ozHMiEiqY_v-LfQyAxsSPOam

### Any Exceptions/special concern?

None

### Telegram username

https://t.me/dpenra

### GitHub username

dpenra

**Comment by tejas101k** [comment]
https://github.com/ProjectInfinity-X/vendor_infinity/blob/QPR3/infinity.devices#L41

Already maintained

**Comment by dpenra** [comment]
please review this device once again for maintainership
