### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by zingrx** [ProjectInfinity-X/official_devices#8]
### Device you want to apply for

Xiaomi 13 (fuxi)

### Device Tree Sources

dt: https://github.com/lolipuru/device_xiaomi_fuxi
kt (prebuilt): https://github.com/lolipuru/device_xiaomi_fuxi-kernel
vt: https://gitlab.com/Skeptcher/vendor_xiaomi_fuxi/

### Number of ROM's you maintain officially/unofficially, also name them

10 (risingOS, ancientOS, AlphaDroid, Matrixx, EvolutionX, PixelOS, Miku, LeafOS, HorizonDroid, SuperiorExtended))

### Any Exceptions/special concern?

I post some of the custom ROMs I build on XDA, but not very frequently. If this a mandatory for maintainer ship, I can adhere for sure. Below are some examples.
https://xdaforums.com/search/71117494/

### Telegram username

zingrx

### GitHub username

zingrx

**Comment by Darkstar085** [comment]
+2 +1 verified..

**Comment by Ghosuto** [comment]
Ben 10 fan

**Comment by zingrx** [comment]
May I know the reason or the criteria of selection bro?

**Comment by tejas101k** [comment]
> May I know the reason or the criteria of selection bro?

the number of roms being mentioned linked to you are pretty high. We look for a maintainer who can focus only on 1-2 roms if preferred.. Also the actual main reason for the rejection is there's not even a fraction of your work being reflected on the resources provided!

**Comment by zingrx** [comment]
Hi Tejas,
I can definitely use my own trees. Check below. I just shared the other links for the one I was intending to build with. On another note, the 10 ROMs I mentioned previously were 2-3 at a time max. I'm currently maintaining Matrixx only.

Hope you consider my request.

https://github.com/zingrx/device_xiaomi_fuxi
https://github.com/zingrx/device_xiaomi_fuxi-kernel

**Comment by Darkstar085** [comment]
@tejas101k approve karde bhai..

**Comment by zingrx** [comment]
hey @tejas101k bro. may I ask for an update?

**Comment by zingrx** [comment]
If it's okay to grant me access to private repos without the official maintainer-ship, it's okay as well.

**Comment by tejas101k** [comment]
> hey @tejas101k bro. may I ask for an update?

maintainership won't be possible here. Really sorry
