### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by artemscine** [ProjectInfinity-X/official_devices#84]
### Device you want to apply for

Redmi Note 12 4G (tapas/topaz)

### Device Tree Sources

https://github.com/openscine/device_xiaomi_topaz
https://github.com/openscine/device_xiaomi_topaz-kernel
https://github.com/openscine/vendor_xiaomi_topaz

### Number of ROM's you maintain officially/unofficially, also name them

ProjectMatrixx, officially 

### Any Exceptions/special concern?

no

### Telegram username

@onlyscine

### GitHub username

artemscine

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
