### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kevin-btw** [ProjectInfinity-X/official_devices#9]
### Device you want to apply for

Moto G60/G40 Fusion (Hanoip)

### Device Tree Sources

Kernel source:
https://github.com/crdroidandroid/android_kernel_motorola_sm7150

Vendor:
https://github.com/crdroidandroid/proprietary_vendor_motorola_hanoip

Device:
https://github.com/crdroidandroid/android_device_motorola_hanoip

### Number of ROM's you maintain officially/unofficially, also name them

1:CrDroid OFFICIAL, 2: LineageOS Unofficial, 3:Evolution Unofficial (Discontinued), 4:DerpFest 

### Any Exceptions/special concern?

None in particular 

### Telegram username

@Sozosha

### GitHub username

@kevin-btw

**Comment by tejas101k** [comment]
DM (t.me/tejas101k).
