### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Notkerd69** [ProjectInfinity-X/official_devices#94]
### Device you want to apply for

Motorola Moto G82 5G (rhodep)

### Device Tree Sources

https://github.com/Keret-Playground/device_motorola_rhodep
https://github.com/Keret-Playground/vendor_motorola_rhodep
https://github.com/Keret-Playground/kernel_motorola_rhodep

### Number of ROM's you maintain officially/unofficially, also name them

1. Unofficially crdroid 2. Unofficially RisingOS

### Any Exceptions/special concern?

As it mentioned here: https://github.com/ProjectInfinity-X/official_devices/issues/62#issue-2368225378
`Device does not have a separate recovery partition So, there are no TWRP or other custom recoveries for this device, Either fastboot packages or boot, dtbo, vendor_boot for recovery.`

### Telegram username

t.me/Notkeret

### GitHub username

Notkerd69

**Comment by tejas101k** [comment]
DM (t.me/tejas101k)
