### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by bezke** [ProjectInfinity-X/official_devices#96]
### Device you want to apply for

Redmi Note 10 pro (sweet)

### Device Tree Sources

[https://github.com/PixelOS-X/device_xiaomi_sweet](url)
[https://github.com/PixelOS-X/device_xiaomi_sm6150-common](url)
[https://github.com/PixelOS-X/vendor_xiaomi_sweet](url)
[https://github.com/PixelOS-X/vendor_xiaomi_sm6150-common](url)
[https://github.com/PixelOS-X/kernel_xiaomi_sm6150](url)

### Number of ROM's you maintain officially/unofficially, also name them

1 (Want only 1 rom, the best)

### Any Exceptions/special concern?

Build roms over 12 years...
Im recognized contributor on xda forum.
Before I was official maintainer on Havoc, Derpfest, Corvus, Resurrection, Ion, etc.....
Now I think, the INfinity has the most intresting source code, so I want to connect to this Team!
The last update came out for sweet on 04 of june!!!!! Please give me this project.
Thanx

### Telegram username

bezke1

### GitHub username

bezke

**Comment by tejas101k** [comment]
The device "sweet" is already maintained as of now, Yes there were some issues with maintainer post 1.1 release but being assured by him that everything will be on track with 1.4 release again, I have to close this issue for now.
