### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by samrth012** [ProjectInfinity-X/official_devices#97]
### Device you want to apply for

Nothing Phone 2 (Pong)

### Device Tree Sources

https://github.com/samrth012/android_device_nothing_Pong
https://gitlab.com/samrth012/vendor_nothing_Pong
https://github.com/samrth012/kernel_nothing_sm8475

### Number of rom(s) you maintain, also name them stating official or unofficial

Unoffical - risingos for pissarro

### Telegram username / or any alternative medium to reach you

samrth012

### GitHub username

samrth012

**Comment by tejas101k** [comment]
too early for official status!

**Comment by samrth012** [comment]
> too early for official status!

Okay, 
Any recommendation when should I apply ?
