### ISSUE TITLE
New maintainer for Redmi note 10, Sunny/Mojito

### ISSUE THREAD

**Issue by dpenra** [ProjectInfinity-X/official_devices#98]
### Device you want to apply for

Redmi note 10, sunny , mojito

### Device Tree Sources

https://gitlab.com/dpenra/android_vendor_xiaomi_sm6150-common
https://gitlab.com/dpenra/android_vendor_xiaomi_mojito.git
https://github.com/dpenra-mojito/android_hardware_xiaomi.git
https://github.com/dpenra-mojito/kernel_xiaomi_mojito.git
https://github.com/dpenra-mojito/device_xiaomi_mojito.git
https://github.com/dpenra-mojito/android_device_xiaomi_sm6150-common.git

### Number of rom(s) you maintain, also name them stating official or unofficial

evolution-x_v9.0, qpr2
evolution-x_v9.2, qpr3
risingOS_v3.2, qpr2
risingOS_v4.0, qpr3
risingOS_v4.1, qpr3
https://drive.google.com/drive/folders/1--KFCyvPlSd74HsdbE3_9tIL95DjT5Zf?usp=sharing
https://t.me/RedmiNote10_Community/425228
https://t.me/RedmiNote10ID/831689
https://mega.nz/file/a5wjkJ7C#hn0rDBOmO-nPmd1qkSlKC1VOjLrzllnPe_3llo5NoeE
https://drive.google.com/drive/folders/1-08zI_26ozHMiEiqY_v-LfQyAxsSPOam

### Any Exceptions/special concern?

Previous maintainer is inactive, and he suggested me to apply for maintainership for this device

### Telegram username / or any alternative medium to reach you

https://t.me/dpenra

### GitHub username

dpenra

**Comment by tejas101k** [comment]
Provided resources couldn't reflect about much contribution of yours! Looks too early for the OFFICIAL status.
