### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Twinchin12** [ProjectInfinity-X/official_devices#99]
### Device you want to apply for

Oneplus 8, 8p, 8t, 9r , Nothing Phone 1

### Device Tree Sources

https://github.com/Twinchin12/teee

### Number of rom(s) you maintain, also name them stating official or unofficial

4

### Telegram username / or any alternative medium to reach you

Twinchin96

### GitHub username

Twinchin12

**Comment by tejas101k** [comment]
trees not accessible
